// <auto-generated />
using AdoptionMVC.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdoptionMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231006011513_restoretable")]
    partial class restoretable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdoptionMVC.Models.Animals", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("img")
                        .IsRequired()
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            age = 3,
                            breed = "Labrador Retriever",
                            description = "Friendly and playful dog",
                            img = "https://images.pexels.com/photos/332612/pexels-photo-332612.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
                            name = "Buddy"
                        },
                        new
                        {
                            ID = 2,
                            age = 2,
                            breed = "Persian",
                            description = "Cuddly and affectionate cat",
                            img = "https://images.pexels.com/photos/7445032/pexels-photo-7445032.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
                            name = "Mittens"
                        },
                        new
                        {
                            ID = 3,
                            age = 4,
                            breed = "Golden Retriever",
                            description = "Loves to go on long walks",
                            img = "https://images.pexels.com/photos/2253275/pexels-photo-2253275.jpeg?auto=compress&cs=tinysrgb&w=300",
                            name = "Max"
                        },
                        new
                        {
                            ID = 4,
                            age = 2,
                            breed = "Boxer",
                            description = "Energetic and adventurous dog",
                            img = "https://images.pexels.com/photos/1294062/pexels-photo-1294062.jpeg?auto=compress&cs=tinysrgb&w=300",
                            name = "Spike"
                        },
                        new
                        {
                            ID = 5,
                            age = 1,
                            breed = "Siamese",
                            description = "Independent and curious cat",
                            img = "https://images.pexels.com/photos/7940675/pexels-photo-7940675.jpeg?auto=compress&cs=tinysrgb&w=300",
                            name = "Whiskers"
                        },
                        new
                        {
                            ID = 6,
                            age = 5,
                            breed = "Maine Coon",
                            description = "Loves to be spoiled with treats",
                            img = "https://images.pexels.com/photos/8942602/pexels-photo-8942602.jpeg?auto=compress&cs=tinysrgb&w=300",
                            name = "Oliver"
                        },
                        new
                        {
                            ID = 7,
                            age = 3,
                            breed = "Beagle",
                            description = "Sweet and gentle dog",
                            img = "https://images.pexels.com/photos/1741235/pexels-photo-1741235.jpeg?auto=compress&cs=tinysrgb&w=300",
                            name = "Luna"
                        },
                        new
                        {
                            ID = 8,
                            age = 2,
                            breed = "Bengal",
                            description = "Playful and friendly cat",
                            img = "https://images.pexels.com/photos/15802496/pexels-photo-15802496/free-photo-of-portrait-of-a-bengal-cat.jpeg?auto=compress&cs=tinysrgb&w=600",
                            name = "Chloe"
                        },
                        new
                        {
                            ID = 9,
                            age = 4,
                            breed = "Rottweiler",
                            description = "Strong and protective dog",
                            img = "https://images.pexels.com/photos/12111334/pexels-photo-12111334.jpeg?auto=compress&cs=tinysrgb&w=1600",
                            name = "Rocky"
                        },
                        new
                        {
                            ID = 10,
                            age = 3,
                            breed = "Siberian",
                            description = "Brave and confident cat",
                            img = "https://images.pexels.com/photos/8369438/pexels-photo-8369438.jpeg?auto=compress&cs=tinysrgb&w=300",
                            name = "Simba"
                        },
                        new
                        {
                            ID = 11,
                            age = 2,
                            breed = "Dachshund",
                            description = "Loves to chase after toys",
                            img = "https://images.pexels.com/photos/169524/pexels-photo-169524.jpeg?auto=compress&cs=tinysrgb&w=600",
                            name = "Milo"
                        },
                        new
                        {
                            ID = 12,
                            age = 4,
                            breed = "British Shorthair",
                            description = "Affectionate and loving cat",
                            img = "https://images.pexels.com/photos/1521306/pexels-photo-1521306.jpeg?auto=compress&cs=tinysrgb&w=600",
                            name = "Lily"
                        },
                        new
                        {
                            ID = 13,
                            age = 2,
                            breed = "Poodle",
                            description = "Eager to learn new tricks",
                            img = "https://images.pexels.com/photos/3299899/pexels-photo-3299899.jpeg?auto=compress&cs=tinysrgb&w=600",
                            name = "Ruby"
                        },
                        new
                        {
                            ID = 14,
                            age = 5,
                            breed = "German Shepherd",
                            description = "Loyal and intelligent dog",
                            img = "https://images.pexels.com/photos/342214/pexels-photo-342214.jpeg?auto=compress&cs=tinysrgb&w=600",
                            name = "Charlie"
                        },
                        new
                        {
                            ID = 15,
                            age = 3,
                            breed = "Ragdoll",
                            description = "Gentle and calm cat",
                            img = "https://images.pexels.com/photos/6441474/pexels-photo-6441474.jpeg?auto=compress&cs=tinysrgb&w=600",
                            name = "Sophie"
                        },
                        new
                        {
                            ID = 16,
                            age = 2,
                            breed = "Cavalier King Charles Spaniel",
                            description = "Loves to snuggle up",
                            img = "https://images.pexels.com/photos/162193/dog-cavalier-king-charles-spaniel-funny-pet-162193.jpeg?auto=compress&cs=tinysrgb&w=600",
                            name = "Teddy"
                        },
                        new
                        {
                            ID = 17,
                            age = 3,
                            breed = "Shih Tzu",
                            description = "Energetic and playful dog",
                            img = "https://images.pexels.com/photos/3361739/pexels-photo-3361739.jpeg?auto=compress&cs=tinysrgb&w=600",
                            name = "Zoe"
                        },
                        new
                        {
                            ID = 18,
                            age = 2,
                            breed = "Scottish Fold",
                            description = "Friendly and social cat",
                            img = "https://images.pexels.com/photos/141496/pexels-photo-141496.jpeg?auto=compress&cs=tinysrgb&w=600",
                            name = "Lola"
                        },
                        new
                        {
                            ID = 19,
                            age = 4,
                            breed = "Akita",
                            description = "Strong and courageous dog",
                            img = "https://images.pexels.com/photos/8601077/pexels-photo-8601077.jpeg?auto=compress&cs=tinysrgb&w=600",
                            name = "Bear"
                        },
                        new
                        {
                            ID = 20,
                            age = 1,
                            breed = "Abyssinian",
                            description = "Loves to explore new places",
                            img = "https://images.pexels.com/photos/13986951/pexels-photo-13986951.jpeg?auto=compress&cs=tinysrgb&w=600",
                            name = "Coco"
                        },
                        new
                        {
                            ID = 21,
                            age = 3,
                            breed = "Russian Blue",
                            description = "Curious and mischievous cat",
                            img = "https://images.pexels.com/photos/18188817/pexels-photo-18188817/free-photo-of-cat-sitting-and-looking-up.jpeg?auto=compress&cs=tinysrgb&w=600",
                            name = "Oscar"
                        },
                        new
                        {
                            ID = 22,
                            age = 2,
                            breed = "Chihuahua",
                            description = "Sweet and affectionate dog",
                            img = "https://images.pexels.com/photos/191353/pexels-photo-191353.jpeg?auto=compress&cs=tinysrgb&w=600",
                            name = "Mia"
                        },
                        new
                        {
                            ID = 23,
                            age = 1,
                            breed = "Oriental Shorthair",
                            description = "Playful and energetic cat",
                            img = "https://images.pexels.com/photos/11943120/pexels-photo-11943120.jpeg?auto=compress&cs=tinysrgb&w=600",
                            name = "Leo"
                        },
                        new
                        {
                            ID = 24,
                            age = 3,
                            breed = "Shetland Sheepdog",
                            description = "Caring and loving dog",
                            img = "https://images.pexels.com/photos/16669178/pexels-photo-16669178/free-photo-of-shetland-sheepdog-on-the-grass-in-summer.jpeg?auto=compress&cs=tinysrgb&w=600",
                            name = "Rosie"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
